name: Daily AI Mentor

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.AIzaSyDcauSCnn3Lft6-5oTsHu65U7cpI7snz6c }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.8470286032:AAF9kMtANwuKxUVXaLXfbYsWqqINOyV4_1I }}
          CHAT_ID: ${{ secrets.6690855328 }}
        run: python main.py
